
export enum EventType {
  DINING_SERVICE = 'DINING_SERVICE',
  PRE_ELABORATION = 'PRE_ELABORATION',
  EXAM = 'EXAM',
  THEORY = 'THEORY',
  LOGISTICS = 'LOGISTICS',
  AUTO_PREP = 'AUTO_PREP',
  AUTO_ALARM = 'AUTO_ALARM',
  AUTO_CRITICAL = 'AUTO_CRITICAL',
  AUTO_MENU_PREP = 'AUTO_MENU_PREP'
}

export interface Category {
  id: string;
  label: string;
  color: string;
  icon: string;
  hasAutoManagement: boolean;
  isSystem?: boolean;
}

export interface CalendarEvent {
  id: string;
  title: string;
  type: string;
  date: string;
  time?: string;
  notes: string;
  isDone: boolean;
  parentId?: string;
  isAutoGenerated?: boolean;
  isUrgent?: boolean;
}

export interface AppSettings {
  iesName: string;
  iesLogo: string;
  profName: string;
  profPhoto: string;
}

export interface AcademicYearRange {
  start: Date;
  end: Date;
}
